### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by BlueArduino20** [a-atalla/tuxcut#10]
``<PyQt4.QtCore.QVariant object at 0x74db5ef0>
Traceback (most recent call last):
  File "./tuxcut.py", line 18, in <module>
    tux = TuxCut()
  File "/home/pi/tuxcut/tuxcut_core.py", line 52, in __init__
    self._gwMAC = self.gw_mac(self._gwIP)
  File "/home/pi/tuxcut/tuxcut_core.py", line 125, in gw_mac
    arping = sp.Popen(['arp-scan','--interface',self._iface,self._gwIP],stdout = sp.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory``

**Comment by aminelch** [comment]
same outpout
